### ISSUE TITLE
Where's datatypes.h ? 

### ISSUE THREAD

**Issue by 2zYoon** [SSGAalto/sfaas#1]
Hi. I'm trying to use S-FaaS in my OpenWhisk platform, but faced some problems.

During build of `enclvae_u.o`  in `sfaas/build/edger8red/`, failed to find a header file, `datatypes.h`.
And it seems that, this header is related to the structures; `resource_measurement_t` and `JS_STATUS`.

Where can I find this header? Although I looked through all of your repositories, I couldn't find it.

Thank you, have a good day. :-)

**Comment by yudhui** [comment]
> 
Hi, did you solve it? I have the same problem.
